In [1]:
import numpy as np

In [3]:
from sklearn.tree import DecisionTreeClassifier

In [101]:
?DecisionTreeClassifier()

In [37]:
a = []

In [38]:
a.append(tree)

In [42]:
a[0].fit()

TypeError: fit() missing 2 required positional arguments: 'X' and 'y'

In [5]:
x = np.concatenate([np.random.exponential(size=200), np.random.normal(size=100)])

In [7]:
x.shape

(300,)

In [8]:
n = len(x)
reps = 10000
xb = np.random.choice(x, (n, reps))

In [10]:
xb.shape

(300, 10000)

In [11]:
?np.random.choice()

In [12]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.random.choice(a, size=10)

array([6, 1, 8, 6, 5, 0, 4, 1, 5, 8])

In [14]:
b = np.arange(120).reshape((30, 4))

In [16]:
b.shape

(30, 4)

In [17]:
b[:3,]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
idx = np.random.choice(np.arange(len(b)), size=len(b))

In [29]:
idx

array([27, 13, 23,  8,  1,  3,  7,  4, 25, 25,  0,  0,  8, 28, 20, 24, 16,
        2,  4, 27,  7, 18, 19, 12, 28, 25, 25, 20,  2, 29])

In [30]:
b[idx]

array([[108, 109, 110, 111],
       [ 52,  53,  54,  55],
       [ 92,  93,  94,  95],
       [ 32,  33,  34,  35],
       [  4,   5,   6,   7],
       [ 12,  13,  14,  15],
       [ 28,  29,  30,  31],
       [ 16,  17,  18,  19],
       [100, 101, 102, 103],
       [100, 101, 102, 103],
       [  0,   1,   2,   3],
       [  0,   1,   2,   3],
       [ 32,  33,  34,  35],
       [112, 113, 114, 115],
       [ 80,  81,  82,  83],
       [ 96,  97,  98,  99],
       [ 64,  65,  66,  67],
       [  8,   9,  10,  11],
       [ 16,  17,  18,  19],
       [108, 109, 110, 111],
       [ 28,  29,  30,  31],
       [ 72,  73,  74,  75],
       [ 76,  77,  78,  79],
       [ 48,  49,  50,  51],
       [112, 113, 114, 115],
       [100, 101, 102, 103],
       [100, 101, 102, 103],
       [ 80,  81,  82,  83],
       [  8,   9,  10,  11],
       [116, 117, 118, 119]])

In [33]:
b[13]

array([52, 53, 54, 55])

In [49]:
b = np.arange(120).reshape((4, 30))
b.shape[1]

30

In [44]:
size = 7

In [48]:
b[:,[1,3,4,9]]

array([[ 1,  3,  4,  9],
       [31, 33, 34, 39],
       [61, 63, 64, 69],
       [91, 93, 94, 99]])

In [50]:
n_cols = b.shape[1]

ensemble_size = 7

In [61]:
col_idxes = np.arange(n_cols)

In [62]:
np.random.shuffle(col_idxes)

In [63]:
col_idxes

array([24, 14, 23, 28, 10, 27, 13, 29, 18, 11, 19,  1,  2,  8,  4, 22,  9,
        3, 12,  0,  6,  5, 16,  7, 20, 21, 17, 26, 15, 25])

In [64]:
n_cols_each = n_cols // ensemble_size

In [65]:
n_cols_each

4

In [66]:
cols_list = []

for i in range(ensemble_size):
    cols_list.append(col_idxes[i*n_cols_each:(i+1)*n_cols_each])

In [67]:
cols_list

[array([24, 14, 23, 28]),
 array([10, 27, 13, 29]),
 array([18, 11, 19,  1]),
 array([ 2,  8,  4, 22]),
 array([ 9,  3, 12,  0]),
 array([ 6,  5, 16,  7]),
 array([20, 21, 17, 26])]

In [94]:
for idx in col_idxes[ensemble_size*n_cols_each:]:
    i = np.random.randint(ensemble_size)
    cols_list[i] = np.append(cols_list[i], idx)

In [70]:
?np.random.randn

In [92]:
np.random.randint(7)

4

In [73]:
?np.random.randint()

In [97]:
aaa = cols_list[1]

In [98]:
aaa

array([10, 27, 13, 29])

In [100]:
b[:, aaa]

array([[ 10,  27,  13,  29],
       [ 40,  57,  43,  59],
       [ 70,  87,  73,  89],
       [100, 117, 103, 119]])

In [102]:
ls

examples.ipynb  README.md  wave.py


In [1]:
from wave import*